//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 214.150957 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_Tanoa {
        displayName = "Syndikat 2023";
        side = 2;
        flag = "\A3\Ui_f\data\Map\Markers\Flags\syndicat_ca.paa";
        icon = "\A3\Ui_f\data\Map\Markers\Flags\syndicat_ca.paa";
        priority = 0;
    };
};//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 214.150957 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////
